spring.application.name=agent
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3:8b

spring.data.redis.host=localhost
spring.data.redis.port=6379